// packages/frontend/src/Detail/HeartZonesDisplay.jsx
import React, { useCallback, useMemo } from 'react';
import DurationDisplay from '../Common/DurationDisplay';
import { hrZonesBg, hrZonesBgStrong, hrZonesText } from '../colors/hrZones';
import { convertHeartDataToZoneSpeeds, convertHeartDataToZoneTimes, convertMetricSpeedToMPH } from '../utils';

const HeartZonesDisplay = ({ zones, nativeZones, heartData, velocityData }) => {
  const totalTimes = useMemo(() => {
    return convertHeartDataToZoneTimes(heartData, zones);
  }, [heartData, zones.z1, zones.z2, zones.z3, zones.z4, zones.z5]);

  const percents = useMemo(() => {
    return totalTimes.map((time) => (100 * time / heartData?.length).toFixed(2));
  }, [totalTimes, heartData?.length]);

  const avg = useMemo(() => convertHeartDataToZoneSpeeds(zones, heartData, velocityData), [heartData, velocityData, zones]);

  const isUsingNonNativeZones = nativeZones.id !== zones.id;

  const Cell = useCallback(({ ix, title, range }) => {
    const isMaxPercentage = Number(percents[ix]) === Math.max.apply(null, percents.map(Number));
    return (
      <div
        className="flex-item-grow"
        style={{
          padding: '1rem',
          background: hrZonesBg[ix + 1],
          border: `1px solid ${isMaxPercentage ? hrZonesBgStrong[ix+1] : hrZonesBg[ix + 1]}`,
          ...isMaxPercentage ? { boxShadow: `inset 0 0 1rem ${hrZonesText[ix+1]}` } : {},
        }}
      >
        <div className="text-center margin-b">
          <b>{title}</b> ({range})
        </div>
          <div className="flex flex-justify-between">
            <div>
              Time in Zone:
            </div>
            <div>
              <DurationDisplay numSeconds={totalTimes[ix]} /> <span>({percents[ix]}%)</span>
            </div>
          </div>
          {avg[ix] && (
            <>
              <div className="flex flex-justify-between">
                <div>
                  Avg Pace in Zone:
                </div>
                <div>
                  <DurationDisplay numSeconds={Math.floor((3660 / convertMetricSpeedToMPH(avg[ix].avg)))} />/mi
                </div>
              </div>
              <div className="flex flex-justify-between">
                <div>
                  Fastest Pace in Zone:
                </div>
                <div>
                  <DurationDisplay numSeconds={Math.floor((3660 / convertMetricSpeedToMPH(avg[ix].max)))} />/mi
                </div>
              </div>
            </>
          )}
      </div>
    );
  }, [avg, percents, totalTimes]);

  return (
    <div>
      {isUsingNonNativeZones && (
        <div>
          <small>Note: Using Non-native Heart Rate Zones</small>
        </div>
      )}
      <div style={{ border: '1px solid black' }}>
        <div className="flex">
          <Cell ix={0} title="Zone 1" range={`${zones.z1} - ${zones.z2 - 1}`} />
          <Cell ix={1} title="Zone 2" range={`${zones.z2} - ${zones.z3 - 1}`} />
          <Cell ix={2} title="Zone 3" range={`${zones.z3} - ${zones.z4 - 1}`} />
          <Cell ix={3} title="Zone 4" range={`${zones.z4} - ${zones.z5 - 1}`} />
          <Cell ix={4} title="Zone 5" range={<span>&ge; {zones.z5}</span>} />
        </div>
      </div>
    </div>
  );
};

export default HeartZonesDisplay;

// packages/vue-frontend/src/components/HeartZonesDisplay.vue
<script lang="ts" setup>
import usePreferencesStore from '@/stores/preferences';
import Surface from './DLS/Surface.vue';
import useHeartZonesStore from '@/stores/heartzones';
import { computed } from 'vue';
import { useActivitiesStore } from '@/stores/activities';
import { convertHeartDataToZoneSpeeds, convertHeartDataToZoneTimes, convertMetricSpeedToMPH, getDurationString } from '@/utils';

const prefStore = usePreferencesStore();
const hrStore = useHeartZonesStore();
const activitiesStore = useActivitiesStore();

const { activity } = defineProps<{ activity: Activity; }>();

const allZones = hrStore.record;
const configZonesId = prefStore.getPreferredHRZoneId();
const nativeZones = hrStore.selectHeartZones(activity.start_date_local);
const heartData = activitiesStore.getStreamTypeData(activity.id, 'heartrate')
const velocityData = activitiesStore.getStreamTypeData(activity.id, 'velocity_smooth');

const zonesId = computed(() => configZonesId === -1 ? nativeZones.id : configZonesId);
const zones = computed(() => allZones.find(({ id }) => id === zonesId) || nativeZones);
const totalTimes = computed(() => convertHeartDataToZoneTimes(heartData, zones.value));
const percents = computed(() => totalTimes.value.map((time) => (100 * time / heartData?.length).toFixed(2)));
const avg = computed(() => convertHeartDataToZoneSpeeds(zones.value, heartData, velocityData));

const isUsingNonNativeZones = computed(() => nativeZones.id !== zones.value.id);
const data = computed(() => {
  const ranges = [
    [zones.value.z1, zones.value.z2 - 1],
    [zones.value.z2, zones.value.z3 - 1],
    [zones.value.z3, zones.value.z4 - 1],
    [zones.value.z4, zones.value.z5 - 1],
    [zones.value.z5]
  ]
  return [1,2,3,4,5].map((n, i) => ({
    title: `Zone ${n}`,
    range: ranges[i],
    percent: percents.value[i],
    timeInZone: getDurationString(totalTimes.value[i]),
    avg: getDurationString(Math.floor((3660 / convertMetricSpeedToMPH(avg.value[i].avg)))),
    max: getDurationString(Math.floor((3660 / convertMetricSpeedToMPH(avg.value[i].max)))),
  }))
});
</script>

<template>
  <Surface class="card">
    <div v-if="isUsingNonNativeZones">
      <small>Note: Using Non-native Heart Rate Zones</small>
    </div>
    <div class="grid full-height">
      <div v-for="(d, ix) in data" class="full-height">
      <div
        :class="`text-center text-body hr-zone-${ix + 1}-bg-light pad full-height`"
      >
        <h3 class="text-h4">{{ d.title }}</h3>
        <div>({{ d.range[0] }} - {{ d.range[1] }})</div>
        <div class="margin-t text-no-wrap">
          <b>Time in Zone:</b>
          <div>
            <span v-if="d.timeInZone">{{ d.timeInZone }}</span>
            <span v-else>--</span>
          </div>
          <div class="text-h5 margin-t">
            ({{ d.percent }}%)
          </div>
        </div>
        <hr />
        <div class="margin-t">
          <b>Average Pace:</b>
          <div>
            <span v-if="d.avg">{{ d.avg }}</span>
            <span v-else>--</span>
          </div>
        </div>
        <div class="margin-t">
          <b>Fastest Pace:</b>
          <div>
            <span v-if="d.max">{{ d.max }}</span>
            <span v-else>--</span>
          </div>
        </div>
      </div>
      </div>
    </div>
  </Surface>
</template>

<style lang="css" scoped>
.grid {
  grid-template-columns: repeat(5, 1fr);
}
</style>
