// packages/frontend/src/Activities/HeatMapContainer.tsx
import { useAppSelector } from '../hooks/redux';
import { success, useGetApiStatus, useTriggerActionIfStatus } from '../reducers/apiStatus';
import { fetchHeatMapDataAct } from '../reducers/activities-actions';
import HeatMapMapLibre from '../Common/HeatMapMapLibre';
import { memo } from 'react';

const HeatMapContainer: React.FC<any> = ({ referenceTime, timeframe }) => {
  const key = [timeframe, referenceTime].filter(Boolean).join('|') || 'all';
  const data = useAppSelector((state) => state.activities.heatMap[key]) || [];

  const action = fetchHeatMapDataAct(timeframe, referenceTime, key);
  
  useTriggerActionIfStatus(action, 'idle');

  const apiStatus = useGetApiStatus(action);

  return (
    <HeatMapMapLibre data={data} measure="total_seconds" deferRender={apiStatus !== success} />
  );
};

export default memo(HeatMapContainer);

// packages/vue-frontend/src/components/HeatMapContainer.vue
<script lang="ts" setup>
import { useActivitiesStore } from '@/stores/activities';
import { computed } from 'vue';
import HeatMap from './HeatMap.vue';
import { useTriggerActionIfStatus } from './hooks/useTriggerActionIfStatus';

type ContainerProps = {
  referenceTime?: string;
  timeframe?: string;
}
const { referenceTime, timeframe } = defineProps<ContainerProps>();

const key = [timeframe, referenceTime].filter(Boolean).join('|') || 'all';
const activitiesStore = useActivitiesStore();
useTriggerActionIfStatus(key, activitiesStore.makeFetchHeatMapData(timeframe, referenceTime));

const data = computed(() => activitiesStore.heatMap[key] || []);
</script>

<template>
<HeatMap :data="data" measure="total_seconds" :deferRender="data.length === 0" />
</template>
