// packages/frontend/src/Common/HeatMap.tsx
import { Button } from '@/DLS';
import Surface from '@/DLS/Surface';
import Shimmer from '@/Loading/Shimmer';
import roundToNearest from '@/utils/roundToNearest';
import Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';
import HighchartsMap from 'highcharts/modules/map';
import { useMemo, useState } from 'react';

HighchartsMap(Highcharts);

const makeSquare = ({ lat, lon }, size = 0.0001) => {
  const delta = size / 2;
  const squareCoords = [
    [lon - delta, lat - delta], // bottom-left
    [lon - delta, lat + delta], // top-left
    [lon + delta, lat + delta], // top-right
    [lon + delta, lat - delta], // bottom-right
    [lon - delta, lat - delta], // bottom-left (to close the square)
    [lon + delta, lat + delta], // top-right (make an X shape)
    [lon + delta, lat - delta], // bottom-right
    [lon - delta, lat + delta], // top-left (make an X shape)
  ];

  return squareCoords;
};

type RGBATuple = [number, number, number, number];

const makeColor = (minColor: RGBATuple, maxColor: RGBATuple, percent: number) => {
  return `rgba(
    ${Math.round(minColor[0] + (maxColor[0] - minColor[0]) * percent)},
    ${Math.round(minColor[1] + (maxColor[1] - minColor[1]) * percent)},
    ${Math.round(minColor[2] + (maxColor[2] - minColor[2]) * percent)},
    ${Math.max(minColor[3], Math.min(maxColor[3], percent))}
  )`;
}

const MINIMUM_SQUARE_SIZE = 0.0001;
const MAXIMUM_SQUARE_SIZE = 0.0004;
const MINIMUM_OPACITY = 0.05;
const DEFAULT_MINIMUM_OPACITY = 0.1;
const MAXIMUM_OPACITY = 1;

type DataPoint = {
  lat: number | string;
  lon: number | string;
  [key: string]: number | string;
};

type HeatMapProps = {
  title?: string;
  data: Array<DataPoint>;
  measure: keyof DataPoint;
  deferRender?: boolean;
  minColor?: RGBATuple; // RGBA
  maxColor?: RGBATuple; // RGBA
  height?: number;
};

const HeatMap: React.FC<HeatMapProps> = ({
  title = 'Heatmap',
  data,
  measure,
  deferRender,
  height = 900,
  minColor = [255, 255, 0, 0.1], // Red with some transparency
  maxColor = [255, 0, 0, 1], // Green with full opacity
}) => {
  const [squareSize, setSquareSize] = useState(MINIMUM_SQUARE_SIZE);
  const [minimumOpacity, setMinimumOpacity] = useState(DEFAULT_MINIMUM_OPACITY);

  const largestValue = useMemo(() => {
    return Math.max(...data.map((d) => Number(d[measure])));
  }, [deferRender]);
  const smallestValue = useMemo(() => {
    return Math.min(...data.map((d) => Number(d[measure])));
  }, [deferRender]);

  const lineSeries = useMemo(() => ({
    type: 'mapline',
    id: 'grid-lines',
    lineWidth: 2,
    data: data.map(({ lat, lon, [measure]: point }) => {
      const percent = (Number(point) - smallestValue) / (largestValue - smallestValue);
      return ({
        geometry: {
          type: 'LineString',
          coordinates: makeSquare({ lat: Number(lat), lon: Number(lon) }, squareSize),
        },
        // color: `rgba(${255}, ${255 * (1 - percent)}, 0, ${Math.max(percent, minimumOpacity)})`,
        color: makeColor(minColor, maxColor, Math.max(percent, minimumOpacity)),
      })
    }),
    showInLegend: false,
    enableMouseTracking: false,
  }), [deferRender, squareSize, minimumOpacity]);

  const options = useMemo(() => {
    return {
      chart: {
        map: 'custom/world',
        animation: false,
        height,
        backgroundColor: 'transparent',
      },
      mapNavigation: {
        enabled: true,
        enableDoubleClickZoom: false,
        enableMouseWheelZoom: false,
      },
      title: {
        text: title,
      },
      series: [lineSeries],
    };
  }, [lineSeries]);

  return (
    <Surface>
      {
        !deferRender
          ? (
            <HighchartsReact
              highcharts={Highcharts}
              constructorType={'mapChart'}
              options={options}
            />
          )
          : <div style={{ height: `${height}px` }}><Shimmer isVisible={true} preset="openBackground" /></div>
      }
      <Button
        onClick={() => setSquareSize(Math.min(MAXIMUM_SQUARE_SIZE, roundToNearest(squareSize + MINIMUM_SQUARE_SIZE, MINIMUM_SQUARE_SIZE)))}
      > Increase Square Size</Button>
      <Button
        onClick={() => setSquareSize(Math.max(MINIMUM_SQUARE_SIZE, roundToNearest(squareSize - MINIMUM_SQUARE_SIZE, MINIMUM_SQUARE_SIZE)))}
      > Decrease Square Size</Button>
      <div className="mt-4">
        <div className="text-body">
          Square Size: {squareSize} | Largest Value: {largestValue}
        </div>
      </div>
      <Button
        onClick={() => setMinimumOpacity(Math.min(MAXIMUM_OPACITY, roundToNearest(minimumOpacity + 0.02, 0.02)))}
      > Increase Min. Opacity</Button>
      <Button
        onClick={() => setMinimumOpacity(Math.max(MINIMUM_OPACITY, roundToNearest(minimumOpacity - 0.02, 0.02)))}
      > Decrease Min. Opacity</Button>
      <div className="mt-4">
        <div className="text-body">
          Minimum Opacity: {minimumOpacity} | Largest Value: {largestValue}
        </div>
      </div>
    </Surface>
  );
};

export default HeatMap;

// packages/vue-frontend/src/components/HeatMap.vue
<script lang="ts" setup>
import {
  MglMap,
  MglGeoJsonSource,
  MglFillLayer,
  MglFullscreenControl,
} from '@indoorequal/vue-maplibre-gl';
import { computed, ref, useId } from 'vue';
import Surface from './DLS/Surface.vue';


type RGBATuple = [number, number, number, number];
type DataPoint = {
  lat: number | string;
  lon: number | string;
  [key: string]: number | string;
};

type HeatMapProps = {
  title?: string;
  data: Array<DataPoint>;
  measure: keyof DataPoint;
  deferRender?: boolean;
  minColor?: RGBATuple; // RGBA
  maxColor?: RGBATuple; // RGBA
  height?: string;
  floorValue?: number;
  ceilingValue?: number;
  squareSize?: number;
};
const {
  data,
  measure,
  deferRender,
  height = '2000px',
  minColor = [20, 20, 255, 0.5], // Red with some transparency
  maxColor = [255, 0, 0, 0.5], // Green with full opacity
  floorValue,
  ceilingValue,
  squareSize = 0.0001,
} = defineProps<HeatMapProps>()

const isDarkReaderMode = true;

let activeMinColor = minColor;
let activeMaxColor = maxColor;
if (isDarkReaderMode) {
  activeMinColor = [255 - minColor[0], 255 - minColor[1], 255 - minColor[2], minColor[3]];
  activeMaxColor = [255 - maxColor[0], 255 - maxColor[1], 255 - maxColor[2], maxColor[3]];
}

const heatmapSource = useId();
const largestValue = computed(() => {
  return Math.max(...data.map((d) => Number(d[measure])));
});
const smallestValue = computed(() => {
  return Math.min(...data.map((d) => Number(d[measure])));
});

const gradientId = useId();

const edges = computed(() => {
  const maxLng = data.reduce((max, { lon }) => Math.max(max, Number(lon)), -Infinity);
  const minLng = data.reduce((min, { lon }) => Math.min(min, Number(lon)), Infinity);
  const maxLat = data.reduce((max, { lat }) => Math.max(max, Number(lat)), -Infinity);
  const minLat = data.reduce((min, { lat }) => Math.min(min, Number(lat)), Infinity);

  return { maxLng, minLng, maxLat, minLat };
});

const initialViewState = computed(() => {
  const deltaLng = edges.value.maxLng - edges.value.minLng;
  const deltaLat = edges.value.maxLat - edges.value.minLat;
  const bounds = [
    edges.value.minLng - deltaLng * 0.1, edges.value.minLat - deltaLat * 0.1,
    edges.value.maxLng + deltaLng * 0.1, edges.value.maxLat + deltaLat * 0.1,
  ] as [number, number, number, number];
  return ({
    bounds,
    pitch: 0,
    bearing: 0,
  })
});

const makeSquare = ({ lat, lon }: { lat: number, lon: number }, size = 0.0001) => {
  const delta = size / 2;
  const squareCoords = [
    [lon - delta, lat - delta], // bottom-left
    [lon - delta, lat + delta], // top-left
    [lon + delta, lat + delta], // top-right
    [lon + delta, lat - delta], // bottom-right
    [lon - delta, lat - delta], // bottom-left (to close the square)
  ] as const;

  return squareCoords;
};
const makeColor = (minColor: RGBATuple, maxColor: RGBATuple, percent: number) => {
  const r = Math.round(minColor[0] + (maxColor[0] - minColor[0]) * percent);
  const g = Math.round(minColor[1] + (maxColor[1] - minColor[1]) * percent);
  const b = Math.round(minColor[2] + (maxColor[2] - minColor[2]) * percent);
  const a = Math.max(minColor[3], Math.min(maxColor[3], percent));
  return `rgba(${r}, ${g}, ${b}, ${a})`;
}
const pointSize = ref(squareSize);
const zoomHandler = (ar: any) => {
  const zoom = ar.map.transform.zoom;
  switch (true) {
    case zoom < 1: return pointSize.value = 0.8;
    case zoom < 2: return pointSize.value = 0.7;
    case zoom < 3: return pointSize.value = 0.6;
    case zoom < 4: return pointSize.value = 0.5;
    case zoom < 5: return pointSize.value = 0.4;
    case zoom < 6: return pointSize.value = 0.3;
    case zoom < 7: return pointSize.value = 0.1;
    case zoom < 8.5: return pointSize.value = 0.01;
    case zoom < 9: return pointSize.value = 0.00066;
    case zoom < 10: return pointSize.value = 0.00047;
    case zoom < 11: return pointSize.value = 0.0003;
    case zoom < 12: return pointSize.value = 0.0002;
    default: return pointSize.value = squareSize;
  }
};

const features = computed(() => {
  return data.map(({ lat, lon, [measure]: point }) => {
    const floor = floorValue !== undefined ? floorValue : smallestValue.value;
    const ceiling = ceilingValue !== undefined ? ceilingValue : largestValue.value;
    if (Number(point) < floor) point = smallestValue.value;
    if (Number(point) > ceiling) point = largestValue.value;
    const percent = (Number(point) - smallestValue.value) / (largestValue.value - smallestValue.value);
    const _features = {
      type: 'Feature',
      geometry: {
        type: 'Polygon',
        coordinates: [makeSquare({ lon: Number(lon), lat: Number(lat) }, pointSize.value)],
      },
      properties: { color: makeColor(activeMinColor, activeMaxColor, percent) },
    } as const
    return _features
  });
})
</script>

<template>
  <Surface class="card" :style="`height: ${height}`">
    <mgl-map
      v-if="!deferRender"
      @map:zoom="zoomHandler"
      map-style="https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json"
      :bounds="initialViewState.bounds"
    >
      <mgl-geo-json-source
        :source-id="heatmapSource"
        :data="{ type: 'FeatureCollection', features }"
      >
        <mgl-fill-layer :layer-id="heatmapSource" :paint="{ 'fill-color': ['get', 'color'] }" />
      </mgl-geo-json-source>
      <mgl-fullscreen-control position="top-right" />
    </mgl-map>
    <div v-if="!deferRender">
      <svg width="100%" height="20">
        <linearGradient :id="gradientId" x1="0%" y1="0%" x2="100%" y2="0%">
          <stop offset="0%" :style="`stop-color: rgb(${activeMinColor[0]}, ${activeMinColor[1]}, ${activeMinColor[2]}); stop-opacity: ${activeMinColor[3]};`" />
          <stop offset="100%" :style="`stop-color: rgb(${activeMaxColor[0]}, ${activeMaxColor[1]}, ${activeMaxColor[2]}); stop-opacity: ${activeMaxColor[3]};`" />
        </linearGradient>
        <rect x="0" y="0" width="100%" height="20" :fill="`url(#${gradientId})`" />
      </svg>
      <div class="flex flex-justify-between">
        <div>
          Lowest ({{ floorValue !== undefined ? `${floorValue} floor` : smallestValue }})
        </div>
        <div>
          Highest ({{ ceilingValue !== undefined ? `${ceilingValue} ceiling` : largestValue }})
        </div>
      </div>
    </div>
  </Surface>
</template>

<style lang="css" scoped>
.container {
  height: 900px;
}
</style>
