// packages/vue-frontend/src/components/ZonesWidth.vue
<script lang="ts" setup>
import { convertHeartDataToZonePercents, convertZonesCacheToPercents } from '@/utils';
import { computed } from 'vue';

type ZonesWidthProps = {
  zones: HeartZone;
  heartData: number[];
  id: number | string;
  zonesCaches: Record<string, HeartZoneCache>;
};
const { zonesCaches, zones, heartData } = defineProps<ZonesWidthProps>();
const percentage = computed(() => {
  if (!zones && !heartData) return [];
  if (zonesCaches?.[zones.id]) return convertZonesCacheToPercents(zonesCaches[zones.id]);
  return convertHeartDataToZonePercents(heartData, zones);
});
</script>

<template>
  <div class="flex width-full">
    <div
      v-for="(percent, ix) of percentage"
      :key="`${ix}-${id}`"
      :class="`hr-zone-${ix + 1}-bg hr-zone-${ix + 1}-border`"
      :style="`width: ${percent}%; height: 1rem; overflow: hidden`"
    ></div>
  </div>
</template>

// packages/frontend/src/Activities/ZonesWidth.jsx
import React, { useMemo } from 'react';
import { convertHeartDataToZonePercents, convertZonesCacheToPercents } from '../utils';
import { hrZonesText } from '../colors/hrZones';

const ZonesWidth = ({ zones, heartData, id, zonesCaches }) => {
  const percents = useMemo(() => {
    if (zonesCaches?.[zones.id]) return convertZonesCacheToPercents(zonesCaches[zones.id]);
    return convertHeartDataToZonePercents(heartData, zones)
  }, [heartData, zones, zonesCaches]);

  if (!zones && !heartData) return null;

  return (
    <div className="flex">
      {percents.filter((n) => Boolean(Number(n))).map((percent, ix) => (
        <div
          key={`${percent}-${ix}-${id}`}
          style={{
            width: `${percent}%`,
            background: hrZonesText[ix + 1],
            border: `1px solid ${hrZonesText[ix + 1]}`,
            height: '0.5rem',
            overflow: 'hidden',
          }}
        />
      ))}
    </div>
  );
};

export default ZonesWidth;
