// packages/vue-frontend/src/ActivityTypesDisplay.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import MultiSelect from './common/MultiSelect.vue';
import { useActivitiesStore } from './stores/activities';
import usePreferencesStore from './stores/preferences';

const prefStore = usePreferencesStore();
const activitiesStore = useActivitiesStore();

const types = computed(() => activitiesStore.activitiesDisplayTypes);

const updateSelectedTypes = (selected: (string | number)[]) => {
  activitiesStore.setDisplayTypes(selected);
  prefStore.setGlobalPreferences({ activityDisplayTypes: activitiesStore.activitiesDisplayTypes });
  prefStore.setUserPreferences();
};

const selectedItems = ref(Object.keys(types.value).filter((k) => types.value[k]));

watch(types, (newTypes) => selectedItems.value = Object.keys(newTypes).filter((k) => !!newTypes[k]));
</script>

<template>
    <div>
      <h2>Activity Types</h2>
      <MultiSelect
        :model-value="selectedItems"
        :options="Object.keys(types).map((displayType) => ({ value: displayType, label: displayType }))"
        :selectedValues="Object.keys(types).filter(type => types[type])"
        @update:model-value="updateSelectedTypes"
      />
    </div>
</template>

export default ActivityTypesDisplay;

// packages/frontend/src/TopNav/ActivityTypesDisplay.tsx
import { MultiSelect } from '@/DLS/MultiSelect';
import { selectActivitiesDisplayTypes } from '@/reducers/activities';
import { setActivitiesDisplayTypesAct } from '@/reducers/activities-actions';
import { setGlobalPrefsAct, triggerSetUserPrefs } from '@/reducers/preferences-actions';
import { useDispatch, useSelector } from 'react-redux';

const ActivityTypesDisplay = () => {
  const types = useSelector(selectActivitiesDisplayTypes);
  const dispatch = useDispatch();

  const updateSelectedTypes = (selected: string[]) => {
    const displayTypes = {
      ...Object.keys(types).reduce((acc, type) => ({ ...acc, [type]: false }), {}),
      ...selected.reduce((acc, type) => ({ ...acc, [type]: true }), {}),
    };
    dispatch(setActivitiesDisplayTypesAct(displayTypes));
    dispatch(setGlobalPrefsAct({
      activityDisplayTypes: displayTypes,
    }));
    dispatch(triggerSetUserPrefs({
      activityDispayTypes: displayTypes,
    }));
  };

  return (
    <div>
      <h2>Activity Types</h2>
      <MultiSelect
        options={Object.keys(types).map((displayType) => ({ value: displayType, label: displayType }))}
        selectedValues={Object.keys(types).filter(type => types[type])}
        onChange={updateSelectedTypes}
      />
    </div>
  );
};

export default ActivityTypesDisplay;
