// packages/vue-frontend/src/TopNav.vue
<script lang="ts" setup>
import ActivityTypesDisplay from './ActivityTypesDisplay.vue';
import Surface from './components/DLS/Surface.vue';
import RecentlyVisitedActivities from './components/RecentlyVisitedActivities.vue';

</script>

<template>
  <Surface variant="foreground">
    <div class="text-body">
      <ActivityTypesDisplay />
      <RecentlyVisitedActivities />
    </div>
  </Surface>
</template>

// packages/frontend/src/TopNav/index.tsx
import React from 'react';
import Surface from '../DLS/Surface';
import ActivityTypesDisplay from './ActivityTypesDisplay';

const TopNav = () => (
  <Surface variant="foreground">
    <div className="text-body">
      <ActivityTypesDisplay />
      {/* <RecentlyVisitedActivities /> */}
    </div>
  </Surface>
);

export default TopNav;
