// packages/vue-frontend/src/views/Calendar.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import dayjs from 'dayjs';
import weekday from 'dayjs/plugin/weekday';
import weekOfYear from 'dayjs/plugin/weekOfYear';
import PageWrapper from '@/components/PageWrapper.vue';
import { useActivitiesStore } from '@/stores/activities';
import Surface from '@/components/DLS/Surface.vue';
import Tile from '@/components/Activities/Tile.vue';

type CalendarDay = { day: number, activities: Activity[]; };

dayjs.extend(weekday);
dayjs.extend(weekOfYear);

const currentMonth = ref(dayjs());
const activitiesStore = useActivitiesStore();

const navigateMonth = (direction: number) => {
  currentMonth.value = dayjs(currentMonth.value).add(direction, 'month');
};

const firstDayOfMonth = computed(() => currentMonth.value.startOf('month').weekday());
const days = computed(() => {
  const dateActivities = activitiesStore.dateGroupedActivities;
  const daysInMonth = currentMonth.value.daysInMonth();
  const weekPlaceholders = [0, 1, 2, 3, 4, 5, 6]
    .map<CalendarDay>((day) => ({ day: day - 7, activities: [] }));
  const tmp = weekPlaceholders.slice(0, firstDayOfMonth.value);
  let daysWithActivities = 0;
  const daysArray = [...Array(daysInMonth)].map((_, i) => i + 1);

  daysArray.forEach(day => {
    const currentDate = currentMonth.value.date(day);
    const currentDayOfWeek = currentDate.day();
    const isWeekend = currentDayOfWeek === 0;
    const formattedDate = currentDate.format('YYYY-MM-DD');

    const hasActivities = dateActivities[formattedDate]?.length > 0;
    if (hasActivities) daysWithActivities++;

    tmp.push({ day, activities: dateActivities[formattedDate] });
  });

  return tmp;
});

const backOneMonth = () => navigateMonth(-1);
const forwardOneMonth = () => navigateMonth(1);
const snapToCurrent = () => currentMonth.value = dayjs();
const weekdayLabels = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
</script>

<template>
  <PageWrapper>
    <div class="text-center text-h1">{{ currentMonth.format('MMMM YYYY') }}</div>
    <div class="flex">
      <button class="text-h4 pad-lr" @click="backOneMonth">&larr;</button>
      <button class="text-h4 pad-lr" @click="snapToCurrent">Snap to Current</button>
      <button class="text-h4 pad-lr" @click="forwardOneMonth">&rarr;</button>
    </div>
    <div class="grid margin-t">
      <Surface v-for="label of weekdayLabels" class="card pad dls-blue-bg text-h4">{{ label }}</Surface>
      <div v-for="day of days" :key="`day-${day.day}-${!!day.activities}`">
        <Surface v-if="day.day > 0" class="card full-height">
          <div v-if="!day.activities" :key="`${day.day}`" class="text-right pad">
            {{ day.day }}
          </div>

          <Tile
            v-for="activity of day.activities"
            :activity="activity"
            :key="activity.id"
            :is-compact="true"
          ></Tile>
        </Surface>

        <div v-else></div>
      </div>
    </div>
  </PageWrapper>
</template>

<style lang="scss" scoped>
.flex {
  display: flex;
  justify-content: center;
  align-items: end;
  gap: calc(var(--space-unit) * 0.5);
}

.grid {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  grid-template-rows: auto repeat(5, 1fr);
  gap: calc(var(--space-unit) * 0.5);
}
</style>

// packages/frontend/src/Calendar/index.tsx
import Tile from '@/Activities/Tile';
import { Basic, Button, Grid } from '@/DLS';
import Surface from '@/DLS/Surface';
import { useAppSelector } from '@/hooks/redux';
import useViewSize from '@/hooks/useViewSize';
import { selectActivitiesByMonth } from '@/reducers/activities';
import dayjs from 'dayjs';
import weekday from 'dayjs/plugin/weekday';
import weekOfYear from 'dayjs/plugin/weekOfYear';
import { useCallback, useMemo, useState } from 'react';

dayjs.extend(weekday);
dayjs.extend(weekOfYear);

const CalendarView = () => {
  const viewSize = useViewSize();
  const [currentMonth, setCurrentMonth] = useState(dayjs());
  const inMonth = useAppSelector(state => selectActivitiesByMonth(state, currentMonth));
  
  const daysInMonth = currentMonth.daysInMonth();
  const firstDayOfMonth = currentMonth.startOf('month').weekday();
  
  const navigateMonth = useCallback((direction: number) => {
    setCurrentMonth(currentMonth.add(direction, 'month'));
  }, [currentMonth]);
  
  const isMobile = viewSize.lte('md');

  const { daysUI, daysWithActivities } = useMemo(() => {
    const days = [];
    let daysWithActivities = 0;
    const daysArray = [...Array(daysInMonth)].map((_, i) => i + 1);
    
    if (!isMobile) {
      for (let i = 0; i < firstDayOfMonth; i++) {
        days.push(<Basic.Div $colorBg="transparent" key={`empty-${i}`} $pad={1}></Basic.Div>);
      }
    }
    
    daysArray.forEach(day => {
      const currentDate = currentMonth.date(day);
      const currentDayOfWeek = currentDate.day();
      const isWeekend = currentDayOfWeek === 0;
      const formattedDate = currentDate.format('YYYY-MM-DD');

      const hasActivities = inMonth[formattedDate]?.length > 0;
      if (hasActivities) daysWithActivities++;

      if (isMobile && isWeekend) {
        days.push(
          <Basic.Div
            $display="flex"
            $flexJustify="space-between"
            key={`weekendMarker-${day}`}
            $color="blue0"
            $pad={0.5}
            $fontSize="h3"
            $borderB="1px solid"
            $marginT={5}
          >
            Sunday
            <div className="blue-0 text-center">
              {day}
            </div>
          </Basic.Div>
        );
      }
      
      days.push(
        <Surface className={`sunken-1 ${hasActivities ? '' : 'p-4'}`} key={`day-${day}`}>
          {!hasActivities && <div className="text-right">{day}</div>}
          {inMonth[formattedDate]?.map((activity) => (
            <div key={activity.id}>
              <Tile key={activity.id} activity={activity} />
            </div>
          ))}
        </Surface>
      );
    });
    
    return {
      daysWithActivities,
      daysUI: days,
    };
  }, [daysInMonth, firstDayOfMonth, currentMonth, inMonth, isMobile]);

  const backOneMonth = useCallback(() => navigateMonth(-1), [navigateMonth]);
  const forwardOneMonth = useCallback(() => navigateMonth(1), [navigateMonth]);
  const snapToCurrent = useCallback(() => setCurrentMonth(dayjs()), []);

  return (
    <div className="max-w-full overflow-x-auto p-2">
      <div className="flex justify-center align-end">
        <div className="text-center">
          <div className="text-h1">
            {currentMonth.format('MMMM YYYY')}
          </div>
          <Button $padL={1} $padR={1} onClick={backOneMonth} $fontSize="h4">
            &larr;
          </Button>
          <Button $padL={1} $padR={1} onClick={snapToCurrent} $fontSize="h4">
            Snap to Current
          </Button>
          <Button $padL={1} $padR={1} onClick={forwardOneMonth} $fontSize="h4">
            &rarr;
          </Button>
        </div>
      </div>
      <div className="mt-8">
        <div className="text-h4">
          {daysWithActivities} days with activities
        </div>
      </div>
      <Grid
        $marginT={2}
        $templateColumns={`repeat(7, 1fr)`}
        $templateColumnsMdDown={"1fr"}
        $templateRows={`auto repeat(6, 1fr)`}
        $templateRowsMdDown="auto"
        $gap={0.5}
      >
        {!isMobile && ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(day => (
          <div
            key={day}
            className="bg-blue-500 p-2 text-white heading-4 sticky top-0"
          >
            {day}
          </div>
        ))}
        {daysUI}
      </Grid>
      
    </div>
  );
};

export default CalendarView;
