// packages/vue-frontend/src/SideNav.vue
<script lang="ts" setup>
import Surface from './components/DLS/Surface.vue';

</script>

<template>
  <div class="side-nav">
    <Surface variant="foreground">
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/calendar">Calendar</RouterLink>
      <RouterLink to="/personal-records">Personal Records</RouterLink>
      <RouterLink to="/volume">Volume</RouterLink>
      <RouterLink to="/multi-map">Multi Map</RouterLink>
      <RouterLink to="/admin">Admin</RouterLink>
    </Surface>
  </div>
</template>

<style scoped>
  .side-nav {
    margin: 0;
    padding: 0;
    width: 200px;
    position: fixed;
    height: 100%;
    overflow: auto;
  }

  /* Sidebar links */
  a {
    display: block;
    padding: 0.5rem 0.5rem;
    text-decoration: none;
    font-weight: bold;
    text-decoration: none;
    font-size: 15px;
    display: block;
  }

  /* Active/current link */
  a:active {
    background-color: #04AA6D;
    color: white;
  }

  /* Links on mouse-over */
  a:hover:not(.active) {
    background-color: #555;
    color: white;
  }

  /* ${(props) => props.theme.breakpoints.down('md')} {
    width: 100%;
    height: auto;
    position: relative;
    a {
      float: left;
      text-align: center;
      float: none;
    } */
</style>

// packages/frontend/src/SideNav/index.tsx
import { type FC } from 'react';
import { Link } from 'react-router-dom';
import styled from 'styled-components';
import { Card } from '../DLS';

type SideNavProps = {};

const SideBar = styled(Card)`
  margin: 0;
  padding: 0;
  width: 200px;
  position: fixed;
  height: 100%;
  overflow: auto;

  /* Sidebar links */
  a {
    display: block;
    padding: 0.5rem 0.5rem;
    text-decoration: none;
    color: blue;
    font-weight: bold;
    text-decoration: none;
    font-size: 25px;
    display: block;
    transition: 0.3s;
  }

  /* Active/current link */
  a:active {
    background-color: #04AA6D;
    color: white;
  }

  /* Links on mouse-over */
  a:hover:not(.active) {
    background-color: #555;
    color: white;
  }

  ${(props) => props.theme.breakpoints.down('md')} {
    width: 100%;
    height: auto;
    position: relative;
    a {
      float: left;
      text-align: center;
      float: none;
    }
}`;

const SideNav: FC<SideNavProps> = () => {
  return (
    <SideBar>
      <Link to="/">Home</Link>
      <hr />
      <Link to="/personal-records">Personal Records</Link>
      <hr />
      <Link to="/volume">Volume</Link>
      <hr />
      <Link to="/multi-map">Multi Map</Link>
      <hr />
      <Link to="/admin">Admin</Link>
    </SideBar>
  );
};

export default SideNav;
