// packages/vue-frontend/src/components/DLS/Surface.vue
<script lang="ts" setup>
type SurfaceProps = {
  variant?: 'base' | 'foreground';
}
const { variant = 'foreground' } = defineProps<SurfaceProps>()
</script>

<template>
  <div :class="variant">
    <slot></slot>
  </div>
</template>

<style>
  @import '../../assets/theme.css';

  .base {
    background-color: var(--color-background);
    color: var(--color-text);
  }

  .foreground {
    background-color: var(--color-foreground);
  }
</style>

// packages/frontend/src/DLS/Surface/index.tsx
import { ForwardedRef, forwardRef } from 'react';
import styles from './surface.module.css'

type SurfaceProps = {
  variant?: 'base' | 'foreground';
  children: React.ReactNode;
  className?: string;
}

const Surface = forwardRef<HTMLDivElement, SurfaceProps>(
  ({ variant = 'foreground', children, className }, ref) => {
    return (
      <div className={`${styles[variant]} ${className}`} ref={ref}>
        {children}
      </div>
    );
  }
)

export default Surface;
